/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ServiPeru;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class TrabajosEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form TrabajosEmpleados
     */
    public void Trabajosporrealizar() throws SQLException{ 
        MetodoConexion pb=new MetodoConexion();
        
        java.sql.Statement st=pb.getConexion().createStatement();
        
       DefaultTableModel Traba=new DefaultTableModel();
        Traba.addColumn("Codigo");
        Traba.addColumn("Nombre de la empresa");
        Traba.addColumn("Tipo de trabajo");
        Traba.addColumn("Fecha de realizacion");
        Traba.addColumn("Lugar de realizacion");
        yaRealizados.setModel(Traba);
        String [] datos = new String [5];
        String Consulta = "select e.Codigo,[Nombre],[Tipo de servicio],[Fecha de realizacion],[Lugar de realizacion] from Servicio e\n" +
                        "inner join Empresas on e.CodigoEmpresa = Empresas.Codigo\n" +
                        "order by [Fecha de realizacion]";
    ResultSet res = st.executeQuery(Consulta);
    while(res.next()){
            datos [0]= String.valueOf(res.getInt(1));
            datos [1]= res.getString(2);
            datos [2]= res.getString(3);
            datos [3]= res.getString(4);
            datos [4]= res.getString(5);
            Traba.addRow(datos);
    }
    st.close();
    }
    public void Trabajosrealiza() throws SQLException{ 
         MetodoConexion pb=new MetodoConexion();
        
        java.sql.Statement st=pb.getConexion().createStatement();

        DefaultTableModel Traba=new DefaultTableModel();
        Traba.addColumn("Codigo");
        Traba.addColumn("Nombre de la empresa");
        Traba.addColumn("Tipo de trabajo");
        Traba.addColumn("Fecha de realizacion");
        Traba.addColumn("Lugar de realizacion");
        PorRealizar.setModel(Traba);
        String [] datos = new String [5];
    String Consulta = "select e.Codigo,[Nombre],[Tipo de servicio],[Fecha de realizacion],[Lugar de realizacion] from ServiciosARealizar e\n" +
                        "inner join Empresas on e.[Codigo de empresa] = Empresas.Codigo\n" +
                          "order by [Fecha de realizacion]";
    ResultSet res = st.executeQuery(Consulta);
    while(res.next()){
            datos [0]= String.valueOf(res.getInt(1));
            datos [1]= res.getString(2);
            datos [2]= res.getString(3);
            datos [3]= res.getString(4);
            datos [4]= res.getString(5);
            Traba.addRow(datos);
    }
    st.close();
    }
    public TrabajosEmpleados() throws SQLException {
        initComponents();
        Trabajosporrealizar();
        Trabajosrealiza();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PorRealizar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        yaRealizados = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Thin", 1, 20)); // NOI18N
        jLabel1.setText("Trabajos por realizar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        PorRealizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(PorRealizar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1010, 290));

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 1, 20)); // NOI18N
        jLabel2.setText("Trabajos realizados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        yaRealizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(yaRealizados);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 1010, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PorRealizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable yaRealizados;
    // End of variables declaration//GEN-END:variables
}
